Bl adding ajax
tluu5/photogram-ajax pull request #1
Opened 2024-10-23 18:43 UTC by tluu5

2024-10-25 21:58 UTC, aldoportillo requested changes
We are missing like and follow functionality

2024-10-25 21:58 UTC, aldoportillo commented on app/views/comments/destroy.js.erb
> +$("#<%= dom_id(@comment) %>").fadeOut(2000, function() {
nice job using this.

2024-10-28 16:50 UTC, jessjno approved these changes

2024-10-28 16:50 UTC, jessjno commented on app/views/comments/_form.html.erb
> +<li id="<%= dom_id(comment.photo) %>_<%= dom_id(comment) %>_form" class="list-group-item">
good job using dom_id

2024-10-28 16:50 UTC, jessjno commented on app/views/follow_requests/_follow_unfollow.html.erb
good job replacing turbo_method

2024-10-28 16:50 UTC, jessjno commented on app/views/follow_requests/create.js.erb
good job using camel case

2024-10-29 21:35 UTC, merged